### ISSUE TITLE
download_coinmarketcap function is not working

### ISSUE THREAD

**Issue by augur2** [deanfantazzini/bitcoinFinance#1]
Error:

download_coinmarketcap_daily("bitcoin",20191201,20191210)

Error in list_from_json$props$initialState$cryptocurrency$ohlcvHistorical[[1]] : 
  subscript out of bounds

**Comment by deanfantazzini** [comment]
Thanks for letting me know about this issue.
Unfortunately, it is clear that coinmarketcap wants to monetize their historical data and they are pushing people to subscribe to their commercial API. This is the third (!!!) change of their website for historical data in less than 1 year. Currently, I have no time to deal with it. If someone can find a solution, please post it here on Github and I will insert it in the package. Thanks!

**Comment by deanfantazzini** [comment]
I corrected the function + I added another function named "bitcoincharts_download_large" which is specifically suited for large files from bitcoincharts.
